sudo: required
services: 
  - docker

before_install:
  - docker build -t dangrinblat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dangrinblat/react-test npm test -- --coverage

after_success:
    - docker build -t dgrinblat/multi-client ./client
    - docker build -t dgrinblat/multi-nginx ./nginx
    - docker build -t dgrinblat/multi-server ./server
    - docker build -t dgrinblat/multi-worker ./worker
    #log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them
    - docker push dgrinblat/multi-client
    - docker push dgrinblat/multi-nginx
    - docker push dgrinblat/multi-server
    - docker push dgrinblat/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-261685751833
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access-key:
    secure: $AWS_SECRET_KEY
    